### ISSUE TITLE
Preview broken in tmux-prev

### ISSUE THREAD

**Issue by Enhancifire** [omerxx/tmux-sessionx#1]
The preview window is broken when using tmux-prev.
It states that no such command was found.

`fish: Unknown command: tmux-prev`
`fish:`
`tmux-prev 'title' | bat --theme TwoDark --style plain`

System Details:
OS: Arch Linux (BTW)
Shell: Fish
Installed packages: fzf, tmux, your plugin

**Comment by omerxx** [comment]
Thanks! You're right. I'll fix and update

**Comment by omerxx** [comment]
@Enhancifire This should be okay now, if you can test and tell me if you can now see preview it'll be great

**Comment by Enhancifire** [comment]
@omerxx Yes that fixed it
Works beautifully. Thanks for fixing!

**Comment by omerxx** [comment]
<kbd>test button<kbd>
