### ISSUE TITLE
Session missing in the list

### ISSUE THREAD

**Issue by invisible1988** [omerxx/tmux-sessionx#10]
I have two sessions with similar names. One of them is missing from the list. (see screenshots)

**tmux-sessionx**
![image](https://github.com/omerxx/tmux-sessionx/assets/5735582/61c69b9e-f304-4360-9fa5-f6edfa3cf23c)

**Default Session Viewer**
![image](https://github.com/omerxx/tmux-sessionx/assets/5735582/412fc049-d6ca-4432-93a7-7576876aed41)

I'm in the session trusted-cms. The session trusted-cms-webdav is missing.

**Comment by omerxx** [comment]
Hey @invisible1988 , is it possible that it's missing because this is the current session?
See the title of the popup. 
If this is the case I'm trying to figure out a non confusing functionality - see #8 (https://github.com/omerxx/tmux-sessionx/issues/8#issuecomment-1850483354)

**Comment by invisible1988** [comment]
Okay, I think I know how the bug appears now. I have two sessions:

- trusted-cms
- trusted-cms-webdav

When I'm in trusted-cms, the trusted-cms-webdav session also disappears. 

I like the feature to hide the current session, but there seems to be a bug in detecting which session I'm in.

**Comment by invisible1988** [comment]
https://github.com/omerxx/tmux-sessionx/blob/d71e51b4be2e94ca5d92f5f8afcc190ac56980f1/scripts/sessionx.sh#L6 #

I think this should fix it.
```shell
(tmux list-sessions | sed -E 's/:.*$//' | grep -v "$CURRENT$") || echo "$CURRENT"
```

**Comment by omerxx** [comment]
@invisible1988 You're perfectly right. I can push the fix or you can open a PR up to you :) Thanks!

**Comment by invisible1988** [comment]
Thanks a lot! Love your extension.
