### ISSUE TITLE
Popup disappears instantly

### ISSUE THREAD

**Issue by hesperaux** [omerxx/tmux-sessionx#110]
New user here.
I installed the plugin, using pretty much all the defaults (see my github dotfiles for tmux config etc.). I have fzf 0.38 so I disabled the legacy support, and I left the sessionx-x-path commented out to use the default (I am not sure what this is actually for, btw).

When I activate the plugin (CTRL+A, o), I see something popup for maybe 50 or 60 milliseconds and immediately disappear. Trying to activate it again has no visible effect.

I'm using continuum and resurrect for session save/restore and have tmux-fzf as well. Any idea what's wrong? How can I debug this?

**Comment by omerxx** [comment]
Hey @hesperaux there are a bunch of things, including version but sounds like you're aware of these.
Did you try running with the legacy support just to see if the issue persists?
Also, I suggest chiming in on [this issue thread](https://github.com/omerxx/tmux-sessionx/issues/22) and if you don't find an answer there feel free to reopen it.
I'll close this one as a duplicate and lets continue the discussion there if you need it!
