### ISSUE TITLE
"Most recently used window" mode? 

### ISSUE THREAD

**Issue by KarateSnowMachine** [omerxx/tmux-sessionx#117]
Hello, 

Thanks for a nice project. One thing I find myself doing quite frequently is switching between two windows back and forth. What I find myself really wanting is the popup to have the most recently used window selected. That way I can just hit `<prefix>o enter` as a sort of quick alt-tab. 

I apologize if my reading of the docs was fast and lazy and if this mode already exists. If it doesn't, do you think it would be difficult/useful to implement? 

Thanks!

**Comment by omerxx** [comment]
Hi!
This is already implemented, emerged here - #111 
Feel free to reopen if this doesn't align with your idea but I'm pretty sure it does :)

**Comment by KarateSnowMachine** [comment]
Updated to latest version and works exactly how I wanted it to. Thanks! (and sorry I did not see the other issue/discussion)

**Comment by mazulo** [comment]
Hi @omerxx sorry for bumping on this old issue, but today just out of nowhere I started getting this weird behavior where the popup does shows up not auto selecting the last visited/used session. Instead it is showing all the windows for each one of the sessions
<img width="3358" alt="Screenshot 2024-11-19 at 11 55 12" src="https://github.com/user-attachments/assets/9440dcdf-627f-4b43-9da5-c28d4c51abb2">

tmux version: 3.4
fzf version: 0.56.3 (brew)

here are the last few lines of my `.tmux.conf` file:
```tmux
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin  'samoshkin/tmux-plugin-sysstat'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'rickstaa/tmux-notify'
set -g @plugin 'sainnhe/tmux-fzf'


# --- tmux-sessionx setup
# Open list of sessions
set -g @sessionx-bind 's'

# When set to 'on' a non-result will be sent to zoxide for path matching
# Requires zoxide installed
# set -g @sessionx-zoxide-mode 'on'

# Window mode can be turned on so that the default layout
# Has all the windows listed rather than sessions only
set -g @sessionx-window-mode 'on'

# If you want to change the prompt, the space is nedded to not overlap the icon
set -g @sessionx-prompt " "

# If you want to change the pointer
set -g @sessionx-pointer "▶ "
```

Would you have any clue on why is this happening?

**Comment by omerxx** [comment]
Hey @mazulo it is weird, although from your screenshot it feels like this is window mode rather than running sessions. if you don't use window mode is this still the case?
if not, could you please open a new issue about last session not working with window mode please?

**Comment by mazulo** [comment]
@omerxx aaah that was it!! I have no idea why/how/when I added this. By changing `@sessionx-window-mode` to off I could get back what I had before. Thanks for pointing this out!
