### ISSUE TITLE
Window closes immidately

### ISSUE THREAD

**Issue by oysandvik94** [omerxx/tmux-sessionx#12]
When i try to trigger it, it closes immidiately. Theres a tiny flash of a popup. Can I find a log somewhere maybe?

**Comment by micheald13** [comment]
I hit this issue also and it is probably due to the version of fzf you have. The below bug has detail

[Ubuntu 22 LTS - fzf-tmux error: unknown option: --border-label](https://github.com/omerxx/tmux-sessionx/issues/9)

**Comment by micheald13** [comment]
> When i try to trigger it, it closes immidiately. Theres a tiny flash of a popup. Can I find a log somewhere maybe?

I hit this issue also and it is probably due to the version of fzf you have. The below bug has detail

[Ubuntu 22 LTS - fzf-tmux error: unknown option: --border-label](https://github.com/omerxx/tmux-sessionx/issues/9)

**Comment by omerxx** [comment]
@oysandvik94 What version of `fzf` are you running? I had multiple users encounter the problem @micheald13 mentioned.
I can add an option to specifically disable the option assuming this is in fact the issue you're facing.
LMK?

**Comment by oysandvik94** [comment]
I was running 0.39 I think (latest in apt), but building from source solved the problem for me, thanks!

**Comment by omerxx** [comment]
@oysandvik94 Gotcha. Closing for now, if this persists / you think requires a fix please open. Thanks!
