### ISSUE TITLE
Installed sucefully but does not launch

### ISSUE THREAD

**Issue by dirad** [omerxx/tmux-sessionx#120]
using fzf 0.50.0
tmux 3.3a

I've installed the plugin with tpm, but invoking it doesn't do anything.
I've tried several different keys.

looking at tmux messages, I dont even see anything trying to run.  As if the key bind doesnt register.

About tmux-fzf , I could not find what is the way in install it* - I'm currently configured fzf to run with "--tmux".
But even without it, i expected something to happen, at least an error...?

* The link to the fzf repo in the README is broken, but i've found the script and made a copy of it as well, in my path.

**Comment by dirad** [comment]
Update - 

Not sure what I did, but now i'm able to see some sessionx related messages in 'show-messages`
Still nothing pops up though.

**Comment by josmas** [comment]
Make sure you also have bat installed. I had a similar issue and it was because I missed the dependencies.

**Comment by the-spanish-guy** [comment]
maybe something here will help you #22

**Comment by dirad** [comment]
fzf should be installed globally . 

* worth adding an error about this somewhere. :pray:
