### ISSUE TITLE
Option to trigger the session manager from terminal or other plugins

### ISSUE THREAD

**Issue by eske4** [omerxx/tmux-sessionx#121]
Great tool!

I've been using a plugin called tmux-which-key that creates a handy menu with options. It would be fantastic to have a straightforward way to trigger sessionx using this menu. It really simplifies remembering commands for my workflow. Leaving option for more custom workflows having external plugins or script trigger an opening of sessionx manager

Best regards,
Eske

**Comment by omerxx** [comment]
Hey @eske4 , maybe I'm missing something, but sounds like this is a feature for the other plugin mentioned, isn't it?

**Comment by eske4** [comment]
The idea was to have an open command that could trigger the navigation menu, allowing it to be opened from external sources. This functionality might already be in place, although I haven't found any documentation on it.

**Comment by omerxx** [comment]
@eske4 If we're talking about a navigation window - that's very much do-able with tmux.
You can have one command that opens a nav pop up with a selection list.
I didn't quite get the last bit with "custom workflows such as custom bash scripts..." can you give and example of what you mean by that?
Like, creating your own custom menu option that triggers a script?

**Comment by eske4** [comment]
Currently, I use a plugin called tmux which-key that can trigger shell commands through a custom shortcut helper menu. I have also thought of various bash scripts; for example, you can have a startup script for tmux with a bash script that triggers tmux with the sessionx menu preopened. Additionally, listener scripts for other tasks that might trigger the menu.

**Comment by omerxx** [comment]
@eske4 sure, but do you think there's place for custom scripts running from within sessionx?
It's technically do-able, the annoyance is probably going to be configuring the menu and the custom scripts.
Maybe it's a standalone plugin of it's own?
Assuming it is, I'll close this issue but please do comment on it (and open if you think it's still relevant in the context of sessionx).
