### ISSUE TITLE
Sessionx popup not working on Debian

### ISSUE THREAD

**Issue by MuradBozik** [omerxx/tmux-sessionx#124]
The session popup window not showing up on Debian machine. Same configuration same versions (both tmux and plugin) works well on Ubuntu machine but not on Debian.

tmux version: tmux 3.3a
fzf version: 0.53 (conda-forge)
os version: Debian GNU/Linux 12.5 (bookworm) x86_64

**Comment by b1tray3r** [comment]
+1

**Comment by Skyr** [comment]
Same problem on Fedora 40. There's a very brief flicker, but the popup won't appear/stay. Not sure if it's the same issue or just my personal fault, I'm just trying it for the first time.

tmux version: 3.4
fzf version: 0.44.1, fzf-tmux present

**Comment by Skyr** [comment]
Had some time digging into that; there's another issue #22 which describes the same symptoms. https://github.com/omerxx/tmux-sessionx/issues/22#issuecomment-1902255317 solved the problem for me.

**Comment by omerxx** [comment]
Hi people of this thread, does `set -g @sessionx-window-mode 'on'` help you at all?
I'm not a debian user so hard for me to replicate the issue

**Comment by MuradBozik** [comment]
I tried, but unfortunately it doesn't help.

**Comment by acristoffers** [comment]
I was also having this problem in NixOS with the Fish shell, and fixed it with the following modifications

```patch
diff --git a/scripts/sessionx.sh b/scripts/sessionx.sh
index 5770c3f..f4a3fdc 100755
--- a/scripts/sessionx.sh
+++ b/scripts/sessionx.sh
@@ -206,7 +206,7 @@ handle_args() {
 		--preview-window="${preview_location},${preview_ratio},,"
 		--layout="$layout_mode"
 		--pointer="$pointer_icon"
-		-p "$window_width,$window_height"
+		--tmux "$window_width,$window_height"
 		--prompt "$prompt_icon"
 		--print-query
 		--tac
@@ -231,7 +231,7 @@ run_plugin() {
 	window_settings
 	handle_binds
 	handle_args
-	RESULT=$(echo -e "${INPUT}" | sed -E 's/✗/ /g' | fzf-tmux "${fzf_opts[@]}" "${args[@]}" | tail -n1)
+	RESULT=$(echo -e "${INPUT}" | sed -E 's/✗/ /g' | fzf "${fzf_opts[@]}" "${args[@]}" | tail -n1)
 }
 
 run_plugin
```

Fish: 3.7.1
tmux: 3.4
fzf: 0.54.1

**Comment by acristoffers** [comment]
Just to be clear, `fzf-tmux` is installed (it comes with tmux) and directly executing the script without modifications prints `mkfifo: invalid mode: invalid digit found in string` to the screen and does nothing. So I started commenting out code to see where the error was and saw it was the the `RESULT=` line. That's when I decided to replace `fzf-tmux` with `fzf --tmux` to see if it worked, and it did.

**Comment by Sammyalhashe** [comment]
I'm having trouble with this on wsl. I have all the prequisites, fzf version 0.40.0, tmux version 3.4. Gone through all the discussion on this that I can find. tmux-fzf popup works for me though so that works for now but really interesting problem.
