### ISSUE TITLE
Is there a way to discard/kill-line?

### ISSUE THREAD

**Issue by mtrajano** [omerxx/tmux-sessionx#125]
This might be a really basic question but I have the habit of using ctrl-u to kill/discard the current line, which is the default behavior in fzf. It looks like this key is overriden by the scroll keybindings. Correct me if I'm wrong but it looks like there's no way to do this in tmux-sessionx at the moment and you're instead forced to delete a character at a time. Would you be open to a pr adding the ability to bind this key? This would be the `unix-line-discard` event in fzf.

**Comment by omerxx** [comment]
Hey, since sessionx is purely based on fzf and it's capabilities, any option can be added!
If you're used to discarding lines I'm happy to add it as a configurable option :)
Feel free to open a PR, or, if others vote this issue I'd find some time to test and add it myself

**Comment by mtrajano** [comment]
Just an update: this wasn't working for me initially when I rebound the scroll-up key to something else but looks like its working now (possibly after I restarted the tmux server or something similar). It's working for my use case now but yes could be worth seeing if anyone wants this feature before implementing so feel free to close the ticket. Thanks for the great software and the awesome videos!

**Comment by madhermit** [comment]
I'd like this feature as well. Or happy to configure it through fzf if you can point me in the right direction for instructions. Thanks!

**Comment by omerxx** [comment]
I'm guessing @mtrajano can share the config here :) I'll close the ticket for now. Reopen if necessary
