### ISSUE TITLE
Incorrect rendering of icons

### ISSUE THREAD

**Issue by garcialn** [omerxx/tmux-sessionx#128]
# Problem
Using Wezterm with NerdFonts, i have some issues with the "Subdirectory" icon `u\{fb0c}`, which has been removed on some of the latest font versions. Because of it, when opening the plugin, the icon apear broken. I'm not sure if there's any other deprecated icon, but from the Wezterm error notification, this seems to be the only example.

![image](https://github.com/user-attachments/assets/3c91d7cf-32b4-4380-9745-ab7ce1db0a4d)
![image](https://github.com/user-attachments/assets/d3efbccc-f570-493e-82d5-1e452c389e51)

# To Reproduce
Simply open the floating panel for Sessionx

# Setup
- Pop!_OS 22.04 LTS
- Wezterm 20240722-080956-7e8fdc11
- Tmux 3.4

# Possible Solution
I believe that just changing the subdir icon to `u\{f060d}` will already solve any issue.

**Comment by omerxx** [comment]
Fixed with #137
