### ISSUE TITLE
Window mode not working when the windows are unnamed/have the same name

### ISSUE THREAD

**Issue by av1155** [omerxx/tmux-sessionx#13]
Window mode does not show the preview of windows if the window has no name (windows have no name by default when created [default 1, 2, 3, etc values do not work]), it also does not switch to the windows (again, if they have no name). Everything else works as expected, previews do show up for sessions, as expected.

When pressing C-w the command works because it expands the session into three to show the three currently active windows for that session; however, it does not show a preview or switch to the selected window of that session (if the window has no name [default 1, 2, 3, etc values do not work]).

Configuration for SessionX:
<img width="1532" alt="Screenshot 2023-12-13 at 2 57 46 PM" src="https://github.com/omerxx/tmux-sessionx/assets/117413846/e4d42f07-7c30-4e4d-8ffa-5342a49846f6">

Step 1: Open the menu without window mode (window mode is off):
<img width="1728" alt="Screenshot 2023-12-13 at 3 02 14 PM" src="https://github.com/omerxx/tmux-sessionx/assets/117413846/48bb9e9b-d389-4dba-b83d-cbde4ebcaf55">

Step 2: When manually triggering window mode with C-w it expands the session into the three currently active windows for that session:
<img width="1728" alt="Screenshot 2023-12-13 at 3 02 28 PM" src="https://github.com/omerxx/tmux-sessionx/assets/117413846/81367e64-774e-410d-a6a3-7376cd65d63d">

Step 3: Cycling through the three windows does not show any preview:
<img width="1728" alt="Screenshot 2023-12-13 at 3 02 31 PM" src="https://github.com/omerxx/tmux-sessionx/assets/117413846/ab13b6d2-ce5c-49eb-b927-e85e507d3164">
<img width="1728" alt="Screenshot 2023-12-13 at 3 02 33 PM" src="https://github.com/omerxx/tmux-sessionx/assets/117413846/b87f3e86-4637-43a7-bd5c-84221a0ecb92">

Step 4: Dotfiles session does show preview, and when selected it goes into the session as expected.
<img width="1728" alt="Screenshot 2023-12-13 at 3 02 36 PM" src="https://github.com/omerxx/tmux-sessionx/assets/117413846/5d70787c-2a4e-4fde-bfa3-79b571785f76">

**Comment by omerxx** [comment]
Indeed an issue. I think most users don't get this as new windows will be configured to use a default name like the default process or another config.

That said, I did reproduce and will look into using IDs rather than names. Thanks!

**Comment by av1155** [comment]
If I rename all windows with the same Nerd Font window icon as a name (automatically, as seen on my Tmux config), the window preview does not work. As pointed out in the original issue, it also does not work as expected when the windows have no names.

<img width="1436" alt="Screenshot 2023-12-14 at 11 58 39 AM" src="https://github.com/omerxx/tmux-sessionx/assets/117413846/e15b8b7e-c7f4-4b0d-bf7c-ec184a829813">

**Here you can see the issue in action:**

<img width="1728" alt="Screenshot 2023-12-14 at 12 03 58 PM" src="https://github.com/omerxx/tmux-sessionx/assets/117413846/d7d5ca87-210e-47af-aba0-5e54d6f1a84e">
<img width="1728" alt="Screenshot 2023-12-14 at 12 04 05 PM" src="https://github.com/omerxx/tmux-sessionx/assets/117413846/10843249-88a5-49a3-acf5-078e0d2a7930">
<img width="1728" alt="Screenshot 2023-12-14 at 12 04 08 PM" src="https://github.com/omerxx/tmux-sessionx/assets/117413846/64f9b7d4-8d84-4ae0-859b-c79b1e56e59f">
<img width="1728" alt="Screenshot 2023-12-14 at 12 04 30 PM" src="https://github.com/omerxx/tmux-sessionx/assets/117413846/24f32c28-00cc-42a4-9ec2-18da16911365">

**After renaming the windows to have different names:**

<img width="1728" alt="Screenshot 2023-12-14 at 12 05 10 PM" src="https://github.com/omerxx/tmux-sessionx/assets/117413846/b6002c6c-3c9d-42eb-8732-68c53519e780">
<img width="1728" alt="Screenshot 2023-12-14 at 12 05 12 PM" src="https://github.com/omerxx/tmux-sessionx/assets/117413846/28287a45-6a5b-417c-80b0-47e03f1af88b">
<img width="1728" alt="Screenshot 2023-12-14 at 12 05 14 PM" src="https://github.com/omerxx/tmux-sessionx/assets/117413846/42a25e55-ac75-4235-a2d9-fc2c98e32db3">
<img width="1728" alt="Screenshot 2023-12-14 at 12 05 15 PM" src="https://github.com/omerxx/tmux-sessionx/assets/117413846/0b6d797f-1e7d-4bdb-bd67-d4406f11c452">

Thanks! I enjoy this plugin.

**Comment by omerxx** [comment]
Got it! Thanks!

**Comment by omerxx** [comment]
@av1155 pushed a fix that addresses windows index rather than names. This works. The problem I think is that winodw names are many times used for describing the workspace with logical names and this takes it away. I'll think of a way to improve the experience
