### ISSUE TITLE
PATH incorrectly loading

### ISSUE THREAD

**Issue by Clay-Ratliff** [omerxx/tmux-sessionx#131]
Hi Omer,

First, let me say thank you for the plugins and videos. They've helped me organize my terminal a great deal.

Issue description:
I've recently installed nix-darwin and played with creating a nix.flake file to begin handling my configuration.
Ever since then, when I try to pull up the preview for the plugin I receive this error:
`line 27: tmux: command not found`
After adding a quick `echo $PATH` to the script, it seems that it no longer contains the path to `/opt/homebrew/bin/tmux`.
Any ideas on why the PATH used by the plugin would be different from the PATH of the shell itself?
My nix configuration is pretty simple right now and looks like this:
File: .config/nix-darwin/flake.nix
   1   │ {
   2   │   description = "My Darwin system flake";
   3   │
   4   │   inputs = {
   5   │     nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
   6   │     nix-darwin.url = "github:LnL7/nix-darwin";
   7   │     nix-darwin.inputs.nixpkgs.follows = "nixpkgs";
   8   │   };
   9   │
  10   │   outputs = inputs@{ self, nix-darwin, nixpkgs }:
  11   │   let
  12   │     configuration = { pkgs, ... }: {
  13   │       # List packages installed in system profile. To search by name, run:
  14   │       # $ nix-env -qaP | grep wget
  15   │       environment.systemPackages =
  16   │         [
  17   │         pkgs.vim
  18   │         ];
  19   │
  20   │       # Auto upgrade nix package and the daemon service.
  21   │       services.nix-daemon.enable = true;
  22   │       # nix.package = pkgs.nix;
  23   │
  24   │       # Necessary for using flakes on this system.
  25   │       nix.settings.experimental-features = "nix-command flakes";
  26   │
  27   │       # Create /etc/zshrc that loads the nix-darwin environment.
  28   │       programs.zsh.enable = true;  # default shell on catalina
  29   │       # programs.fish.enable = true;
  30   │
  31   │       # Set Git commit hash for darwin-version.
  32   │       system.configurationRevision = self.rev or self.dirtyRev or null;
  33   │
  34   │       # Used for backwards compatibility, please read the changelog before changing.
  35   │       # $ darwin-rebuild changelog
  36   │       system.stateVersion = 4;
  37   │
  38   │       # The platform the configuration will be used on.
  39   │       nixpkgs.hostPlatform = "x86_64-darwin";
  40   │       security.pam.enableSudoTouchIdAuth = true;
  41   │
  42   │       system.defaults = {
  43   │         dock.autohide = true;
  44   │         dock.mru-spaces = false;
  45   │         finder.AppleShowAllExtensions = true;
  46   │         finder.FXPreferredViewStyle = "clmv";
  47   │         loginwindow.LoginwindowText = "Aiven";
  48   │         screencapture.location = "~/Pictures/screenshots";
  49   │         screensaver.askForPasswordDelay = 10;
  50   │       };
  51   │     };
  52   │   in
  53   │   {
  54   │     # Build darwin flake using:
  55   │     # $ darwin-rebuild build --flake .#Clays-MacBook-Pro
  56   │     darwinConfigurations."Clays-MacBook-Pro" = nix-darwin.lib.darwinSystem {
  57   │       modules = [ configuration ];
  58   │     };
  59   │
  60   │     # Expose the package set, including overlays, for convenience.
  61   │     darwinPackages = self.darwinConfigurations."Clays-MacBook-Pro".pkgs;
  62   │   };
  63   │ }

**Comment by omerxx** [comment]
Hey @Clay-Ratliff this sounds like more of a discussion and one that's relevant to your flake config rather than the plugin itself.
So with your permission I'll close this, feel free to open a discussion (or comment here), you'd probably find better luck with the contributors helping with with the flake in the project.
I can't think myself of a reason why your path would change while running the plugin specifically...

**Comment by Clay-Ratliff** [comment]
Sounds reasonable, thanks for the response.
