### ISSUE TITLE
Question about previewing and Feature-Request for after deleting attached session with filter-current true

### ISSUE THREAD

**Issue by Atan-D-RP4** [omerxx/tmux-sessionx#134]
I configured the plugin to display the paths for new sessions using the custom-paths option alongside the active sessions. The only problem is that the file paths I have showing up are not previewed.

I'd previously modified my sessionizer script to show a directory listing for those 'maybe-sessions' file-paths.

Is there a way to do the same with plugin? I tried to modify the preview.sh script a bit. But couldn't find a way to do it in 10 minutes, so I thought I'd ask.

This is what I'm talking about:
![Screenshot (99)](https://github.com/user-attachments/assets/b31cd414-c779-4afd-93ac-6df939b52f80)

Also, this is the modification to the preview script I tried. Don't know if I'm on the right track.
![Screenshot (101)](https://github.com/user-attachments/assets/e43851d6-4689-4ed1-8f51-027038b34310)

Also, also!
With the filter-current option set to true, you are able to see the current session you are attached. Meaning it can be killed with the default alt-backspace command. Doing so exits tmux. While that behavior is understandable I would want it to attach to one of the other available sessions or maybe create a default templated session. 

Options for configuring that would be nice.

**Comment by danitrap** [comment]
Hey @Atan-D-RP4, I think my pull request #161 should do the trick! let me know.

Also, I think you need this setting in your tmux config: `set -g detach-on-destroy off`

```
       detach-on-destroy [off | on | no-detached | previous | next]
               If on (the default), the client is detached when the
               session it is attached to is destroyed.  If off, the
               client is switched to the most recently active of the
               remaining sessions.  If no-detached, the client is
               detached only if there are no detached sessions; if
               detached sessions exist, the client is switched to the
               most recently active.  If previous or next, the client is
               switched to the previous or next session in alphabetical
               order.
```

**Comment by Atan-D-RP4** [comment]
Awesome work! Never did manage to make it work on my own.

Closing this issue since it is now resolved/implemented.
