### ISSUE TITLE
Use different Glyph for Tree Mode

### ISSUE THREAD

**Issue by itsfergi** [omerxx/tmux-sessionx#136]
The unicode char  `u\(fb0c)` used in Tree Mode was moved to `u\(f060d)` in Nerd Fonts 3.0.0.
My suggestion would be to update the glyph   to `u\(f060d)` or better yet make it customizable like `sessionx-pointer` and `sessionx-prompt`.

**Comment by itsfergi** [comment]
- Created a Pullrequest #137

**Comment by omerxx** [comment]
should be fixed with the recent merge, please feel free to reopen if something changes
