### ISSUE TITLE
[Feature request]: Window mode toggle

### ISSUE THREAD

**Issue by omerxx** [omerxx/tmux-sessionx#14]
From Reddit: 
> it would be nice if "window mode" can be a toggle of some kind, meaning that you can go to window mode and come back to session mode etc.

**Comment by arnevm123** [comment]
Adding to this: It would be nice if we could go straight to "create new session" and "window" mode with a combo from within tmux.
eg. prefix-o opens the default window and prefix-s opens the "create a new session" (instead of prefix-o C-x now)

**Comment by omerxx** [comment]
@arnevm123 re "going straight to create new session" - the things is, you're basically there, you hit `ctrl-o` type a name and hit enter, as long as its not on the list, a new session with that new will be created. So I don't see a point in having a dedicated mode, do you? 

Re going to window mode, you have a binding to set window mode as default. If you still like a way to trigger window mode with a given prefix that can be done. Given the binding for default behaviour, still relevant?

**Comment by arnevm123** [comment]
@omerxx The difference is (I think) that when creating a session from select session mode does not help me chose which folder will be my tmux root folder for that session and no fuzzy finding my sessions. (Unless I'm missing something?)

**Comment by omerxx** [comment]
Maybe I'm missing something - when you launch the plugin you can can fuzzy search existing plugins or create a new one from a name that's not on the list, this is automatic.
As for the default path that's more of a basic tmux config, but what you can do is switch on zoxide mode which will try and grab your given name from a list of history zoxide searches.

Does that help?
Are you expecting something else? Maybe an option to provide a path to a new session you want to create?

**Comment by omerxx** [comment]
Please reopen if this is still relevant
