### ISSUE TITLE
Starting tmuxinator session returns 1

### ISSUE THREAD

**Issue by snikoletopoulos** [omerxx/tmux-sessionx#147]
When selecting session from tmuxinator it loads the session but throws this error:
`'/Users/snikoletopoulos/.config/tmux/plugins/tmux-sessionx/scripts/sessionx.sh' returned 1`

This is my sessionx config for tmuxinator:
```tmux
set -g @sessionx-tmuxinator-mode "on"
set -g @sessionx-bind-tmuxinator-list "alt-t"
```

After I press enter on the pane with the error everything works fine.

Let me know if I can help with this.

**Comment by Rasmus-Bertell** [comment]
Might have been introduced in #143, I can take a look if I can reproduce this.

**Comment by omerxx** [comment]
@snikoletopoulos any updates regarding @Rasmus-Bertell's comment?
@Rasmus-Bertell can you try and reproduce please?

**Comment by Rasmus-Bertell** [comment]
Haven't had the time yet to do this, but I'll get to it as soon as I can.

**Comment by Rasmus-Bertell** [comment]
Finally had some time to look at this. Bash scripting isn't really my forte so this was something that confused me. Seems like bash functions use the return value of the previously called function so I added an explicit exit statement to the end of output handling to always return true.
