### ISSUE TITLE
Ctrl-x Fuzzy Read command not found on macOS

### ISSUE THREAD

**Issue by zaperrer** [omerxx/tmux-sessionx#148]
When using Ctrl-e or Ctrl-x an error is returned:
`[Command failed: find .dotfiles -mindepth 1 -maxdepth 1 -xtype d]`
I expect this is due to the xtype argument not being available in the macOS find command as opposed to the gnu version.
When running that command directly an error is returned:
`find: -xtype: unknown primary or operator`
I also do not see xtype listed in my man page for find.

**Comment by omerxx** [comment]
Good catch, reproduced. I wonder whats the best way forward here. I'd like to keep the functionality available for all platforms available

**Comment by omerxx** [comment]
This was introduced by #142
Working on a fix

**Comment by zaperrer** [comment]
Works great now, thanks!
