### ISSUE TITLE
Sessionx Nix Package

### ISSUE THREAD

**Issue by okwilkins** [omerxx/tmux-sessionx#149]
Hey,

Was looking around on [Nix Pkg](https://github.com/search?q=repo%3ANixOS%2Fnixpkgs%20sessionx&type=code) and couldn't help but notice that this project isn't on there. Am I missing something here? Would really like to have this in Nix Packages as I use [Devbox](https://www.jetify.com/devbox) and I don't think I can install the flake without it.

**Comment by okwilkins** [comment]
https://github.com/NixOS/nixpkgs/pull/343750
I have decided to have a go myself!

**Comment by omerxx** [comment]
> https://github.com/NixOS/nixpkgs/pull/343755
> 
> I have decided to have a go myself!

Oh wow!
Thank you!

**Comment by okwilkins** [comment]
Big fan of your work, nice to be able to give back in some small way!


![](https://i.kym-cdn.com/entries/icons/original/000/028/021/work.jpg)

**Comment by omerxx** [comment]
I'll go ahead and close this but if the nixpkgs PR doesn't get merged feel free to reopen!
