### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by suvasanket** [omerxx/tmux-sessionx#15]
After pressing the prefix+o a window seems to appear for a split second and then disappears
all the Prerequisits are installed 
here is the code

``` 
set -g @plugin 'tmux-plugins/tpm'
#井 H##I#### Plugins 拼
set -g @plugin 'joshmedeski/t-smart-tmux-session-manager'
set -g @t bind 'a'

set -g @plugin 'omerxx/tmux-sessionx'

set -g @plugin 'sainnhe/tmux-fzf'
TMUX_FZF_LAUNCH_KEY="f"
set -g @plugin 'trevarj/tmux-open-nvim'
set -g @plugin 'thesast/tmux-keylocker'
set -g @keylocker-toggle-bind 'F3'
set -g @plugin "tmux-plugins/tmux-resurrect'
set -g @resurrect-capture-pane-contents 'on'
set -g @plugin "tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
```

**Comment by omerxx** [comment]
@suvasanket Hard for me to say, I test every release but this may be conflicting with some other installation you have running there. Are you up to date with the recent push? You can run `<prefix> + U` to update and make sure.
Are you able to read what it says before it crashes by any chance?
You can try and forward stderr to a logfile from `sessionx.tmux`

**Comment by suvasanket** [comment]
I've reinstalled all things but still no luck
And there is no error or anything after crash it just doesn't open 😔

**Comment by omerxx** [comment]
@suvasanket Thinking of a way I can help...
I can try replicating your env, just need to know your
- fzf version
- bat version

**Comment by jessesung** [comment]
I can reproduce the issue with an Ubuntu 22.04. `fzf` in 22.04 is `0.29 (devel)` which does not support these four parameter lines:
```
--bind 'focus:transform-preview-label:echo [ {} ]'
--border-label "Current session: \"$CURRENT\" "
--color 'preview-border:236,preview-scrollbar:0'
--color 'preview-border:236,preview-scrollbar:0'
```
After removing them from `scripts/sessionx.sh`, `fzf-tmux` window shows without an issue.

**Comment by omerxx** [comment]
@jessesung Yep, this is a known (but different issue) of an old fzf version which IIRC doesn't know the `--border-label` configuration. Current fzf is `0.44` so you may want to update.
If not, I can suggest a dedicated configuration that when set, the plugins won't try to use the border label.
Either than or a small readme "known issue". WDYT?

**Comment by jessesung** [comment]
Another option may be checking the fzf version before passing extra parameters?

**Comment by suvasanket** [comment]
Will try
Thx for the reply

**Comment by omerxx** [comment]
> Another option may be checking the fzf version before passing extra parameters?

Sure I can test the version but then it's this limbo of how many breaking changes and versions are you going to support.
If you guys think it makes sense then sure, either than or I'd just add a small warning with the version + way to fix.

**Comment by omerxx** [comment]
@jessesung TBH this was introduced on [0.34](https://github.com/junegunn/fzf/releases/tag/0.35.0)
I'll add a readme and a small change to help fixing if possible!
