### ISSUE TITLE
How fast is SessionX supposed to be?

### ISSUE THREAD

**Issue by SebastianMusic** [omerxx/tmux-sessionx#153]
Hello, i have started using SessionX and enjoy being able to fuzzy find over my tmux sessions, it is great!
The only issue is that i feel like it always lags a bit. at least compared to the normal prefix+s which feels instant.

So i am wondering if SessionX also is supposed to be instant, and there is a bug on my end, or if everything is like it is supposed to be. I have attached a video with my keys on the bottom left corner.  ctrl+s is my prefix and shift o is what i use to open sessionx, you can see there is a lag between when i press and it opens.

https://github.com/user-attachments/assets/f40f4eb2-b900-46d9-a136-9cb1acb000ac

**Comment by IniyanKanmani** [comment]
I am having the same issue. It does take like a second to pop up.

**Comment by praveshishere** [comment]
there already exists an issue for the same, please track on https://github.com/omerxx/tmux-sessionx/issues/123
