### ISSUE TITLE
Sessionx pop up doesn't open

### ISSUE THREAD

**Issue by praveshishere** [omerxx/tmux-sessionx#156]
I formatted my system, so reinstalled tmux and sessionx, but when I use prefix + o nothing happens, the key is correct as per tmux.conf, fzf and fzf-tmux work on in terminal as normal.

Please help if any ideas

**Comment by Marat-Gumerov** [comment]
Try:
```
cd ~/.config/tmux/plugins/tmux-sessionx
bash -x scripts/sessionx.sh
```
This will try to open the popup window and print lots of logs for debugging purposes

**Comment by praveshishere** [comment]
> Try:
> 
> ```
> cd ~/.config/tmux/plugins/tmux-sessionx
> bash -x scripts/sessionx.sh
> ```
> 
> This will try to open the popup window and print lots of logs for debugging purposes

I tried this, and it did open the popup, I have the logs here
https://github.com/praveshishere/links/blob/main/sessionx_output.log

if you could help find the issue, I see no failures in log

**Comment by Marat-Gumerov** [comment]
But it shouldn't open :) Because `bash scripts/sessionx.sh` does the exact same thing as the prefix + o binding does.
I know it is stupid, but, can you try the following code for the binding?
```
bind-key -n F1 "run-shell \"cd ~/.config/tmux/plugins/tmux-sessionx && ~/.config/tmux/plugins/tmux-sessionx/scripts/sessionx.sh\""
```
This code should be added to the end of tmux.conf. It binds the F1 key to the popup

**Comment by praveshishere** [comment]
I don't know but for some reason it has started working, 

> But it shouldn't open :) Because `bash scripts/sessionx.sh` does the exact same thing as the prefix + o binding does. I know it is stupid, but, can you try the following code for the binding?
> 
> ```
> bind-key -n F1 "run-shell \"cd ~/.config/tmux/plugins/tmux-sessionx && ~/.config/tmux/plugins/tmux-sessionx/scripts/sessionx.sh\""
> ```
> 
> This code should be added to the end of tmux.conf. It binds the F1 key to the popup

I also added the f1 key binding as you said, so now it's easier to open :).
