### ISSUE TITLE
i cant figure out how to make the window transparent

### ISSUE THREAD

**Issue by isak79** [omerxx/tmux-sessionx#160]
everything in my terminal is transparent, but i cant figure out how to make sessionx transparent as well.

this is mye tmux config:

set -g default-terminal "xterm-256color"
set-option -g terminal-overrides ',xterm-256color:RGB'

set -g status-style fg=default,bg=default

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

set -g set-clipboard on   

unbind %
bind "'" split-window -h

unbind '"' 
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind * setw synchronize-panes

bind -r m resize-pane -Z

set -g mouse on
set -g base-index 1    
set -g renumber-windows on
set -g default-terminal "${TERM}"

set-window-option -g mode-keys vi

bind å copy-mode
bind-key -T copy-mode-vi 'v' send -X begin-selection 
bind-key -T copy-mode-vi 'y' send -X copy-selection 

unbind -T copy-mode-vi MouseDragEnd1Pane

# Ensure that everything on the right side of the status line
# is included.
set-option -g status-position top

# tmux plugin
set -g @plugin 'tmux-plugin/tpm'

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves tmux sessions every 15 minutes
set -g @plugin 'omerxx/tmux-sessionx'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-fzf-builtin-tmux 'on'
set -g @sessionx-bind-scroll-up 'alt-p'
set -g @sessionx-bind-scroll-down 'alt-n'

set -g @plugin 'catppuccin/tmux#v2.1.0'
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_status_background "default"
set-option -g automatic-rename on
set -g status-right "#{E:@catppuccin_status_application}#{E:@catppuccin_status_session}"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W#{?window_zoomed_flag,(),}"

set -g status-left ""
set -g status-right-length 50
set -g status-left-length 50

set -g @plugin 'omerxx/tmux-floax'
set -g @floax-bind 'e'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
# initialize tmux plugin manager
run '~/.tmux/plugins/tpm/tpm'
![Uploading Screenshot 2024-12-10 at 16.21.26.png…]()

**Comment by johnnguyencodes** [comment]
I had the same issue, but I resolved it by adding this line to your .tmux.conf file, I find it only works if you place it after your settings for catppuccin.  

set -g popup-style 'bg=default'

**Comment by isak79** [comment]
that worked, thank you

**Comment by omerxx** [comment]
Happy this is resolved. I'll close but if there's an issue to be fixed please reopen.
