### ISSUE TITLE
Plugin is not working

### ISSUE THREAD

**Issue by mkhattat** [omerxx/tmux-sessionx#163]
I just updated all my plugins, and suddenly, I can not open the tmux session. Upon pressing the key binding I had, the window flashes and closes. 

It probably has something to do with the last 2 commits (merge pull requests) because if I reset back to the commit `bc6376fa66bd3b8214b5c9b20c93c34ab43fe98e`, everything works again.

**Comment by heywhy** [comment]
i'm facing the same issue after updating

**Comment by sigthror** [comment]
It looks like is problem in https://github.com/omerxx/tmux-sessionx/pull/155, because `bc6376fa66bd3b8214b5c9b20c93c34ab43fe98e` doesn't include this changes

**Comment by heywhy** [comment]
The below line causes this issue. It utilizes the associative array feature, available only in recent Bash versions (v4 upwards). Upgrading Bash fixes this problem.

https://github.com/omerxx/tmux-sessionx/blob/4f58ca79b1c6292c20182ab2fce2b1f2cb39fb9b/sessionx.tmux#L156

**Comment by sigthror** [comment]
Sorry, you are right, my bad. Thanks for the answer!

**Comment by mkhattat** [comment]
Thanks @heywhy. I confirm updating the bash solves the problem. I am closing this issue.
