### ISSUE TITLE
Window closes immediately

### ISSUE THREAD

**Issue by snikoletopoulos** [omerxx/tmux-sessionx#164]
When I press `<prefix>o` I can see the sessionx window for a brief moment and immediately it disappears.

The issue started as soon as I updated sessionx, not sure which version I had last.
I'm on the latest tmux and sessionx at the moment.

**Comment by sigthror** [comment]
You can try https://github.com/omerxx/tmux-sessionx/issues/163

**Comment by snikoletopoulos** [comment]
That was the problem. Updating bash solved it, thanks!
