### ISSUE TITLE
window switcher is not working 

### ISSUE THREAD

**Issue by conXDlation** [omerxx/tmux-sessionx#18]
![image](https://github.com/omerxx/tmux-sessionx/assets/139586557/b97c69a6-6857-4e19-8ebc-46038a242031)
can say much it says error in sessionx.sh

**Comment by omerxx** [comment]
@conXDlation What's your `fzf` version + `bat` version, and do you have any special config for the plugin in your tmux.conf file other than the import?

**Comment by omerxx** [comment]
@conXDlation Found the issue and fixed it. Unfortunately now this means I can't show window names on window mode. Let me know how bad is it and I'll see what can be done.

**Comment by av1155** [comment]
I wanted to follow up on [conXDlation](https://github.com/conXDlation)'s issue. I was experiencing the same problem, but your recent commit resolved it. Now, I can preview and seamlessly switch between different windows in a session without encountering the '.../.../.../ returned 1' error. This plugin has proven to be exactly what I was looking for – thank you for your excellent work!

I understand this was initially developed for your personal use. For my purposes, the window name visibility isn't an issue as long as the core functionality – effectively previewing and navigating between windows in a session – is maintained. The inclusion of the window number is particularly useful!

The commit I am referring to: [fix](https://github.com/omerxx/tmux-sessionx/commit/1f395801c37bc18af0a1b5b64bf2265799c4a3f7) https://github.com/omerxx/tmux-sessionx/issues/18 [window switcher only works with index now. need to find a way to incorporate names](https://github.com/omerxx/tmux-sessionx/commit/1f395801c37bc18af0a1b5b64bf2265799c4a3f7)

**Comment by omerxx** [comment]
Perfect! Happy to hear!
It was indeed built for my workflow but with others using it I'm responsible for all advertised features to work flawlessly. So I'm happy it works and you feel any other functionality is missing feel free to open an issue / LMK

Thanks!
