### ISSUE TITLE
Rename does not work in fish shell

### ISSUE THREAD

**Issue by kanwarujjaval** [omerxx/tmux-sessionx#20]
The rename commands errors out with Variables cannot be bracketed.

The top also shows strings from somewhere and this is something that is also auto read by the rename command, ( does not take input)

<img width="1044" alt="Screenshot 2023-12-27 at 11 22 47 AM" src="https://github.com/omerxx/tmux-sessionx/assets/4216199/d668aaf3-0637-457f-9f31-473d8b7f5184">

My tmux conf
```
setw -g mouse on
# ctrl-a as prefix instead of ctrl-b
unbind C-b
set -g prefix C-a
# 'C-a C-a' sends C-a keypress to the current window
bind C-a send-prefix
set-window-option -g mode-keys vi
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tmux-sensible'
#set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark'
run '~/.tmux/plugins/tpm/tpm'
```

**Comment by kanwarujjaval** [comment]
Its the rename for me, but also the default names are displayed incorrectly it seems (as in the screenshot)

**Comment by omerxx** [comment]
I can see why, I'm working with ZSH, maybe this requires some docs clarification, or, if you can find a better method for fish I'd be happy to integrate it

**Comment by BigJayToDaIzo** [comment]
> I can see why, I'm working with ZSH, maybe this requires some docs clarification, or, if you can find a better method for fish I'd be happy to integrate it

Another fish shell user bummed out by a 'broken' rename functionality. The rest seems to work flawlessly for me so far.  Thanks for a great product and ideally one of us open sourcers can figure out how to integrate 'full fish shell' support! I'm not a shell scripter by nature but I've been wanting to be more proficient customizing my box so I'll dive into the .sh to try to help.

**Comment by Meliketoaste** [comment]
I am 90 percent sure this is also an issue with nushell. Because i had issues with nushell not beeing able to rename as well. And changed default shell to zsh and now it works.
