### ISSUE TITLE
Usage as a flake module?

### ISSUE THREAD

**Issue by jtara1** [omerxx/tmux-sessionx#29]
Has anyone used or tested this as a flake module?

Looks like there's some generic instructions probably autogenerated in https://github.com/omerxx/tmux-sessionx/blob/main/flake.nix#L11

```
        # To import a flake module
        # 1. Add foo to inputs
        # 2. Add foo as a parameter to the outputs function
        # 3. Add here: foo.flakeModule
```

Doesn't look like this works for me or `tmux-sessionx.flakeModule` is defined checking `nix flake show github:omerxx/tmux-sessionx --no-write-lock-file`

I have it setup to use as a tmux plugin with `tmux-sessionx.packages.x86_64-linux.default`, but I'm missing something still.

**Comment by omerxx** [comment]
The integration was create by @schromp who may be able to help

**Comment by schromp** [comment]
Whoops this documentation is a leftover from the flake-parts example and should be removed. My bad.

How to actually use:
1. Adding inputs.tmux-sessionx.url = "github:omerxx/tmux-sessionx"; to your system flake
2. Adding programs.tmux.plugins = [ inputs.tmux-sessionx.packages."x86_64-linux".default ]; into the home-manager or system configuration

I'll do a pr later to remove the docs from the flake and add some actual instructions to the docs.

**Comment by schromp** [comment]
I have raised a PR adding some documentation.
Im also going to look into upstreaming the plugin into nixpkgs to remove the need for the flake.
This could take some time to land in non unstable then though.

**Comment by omerxx** [comment]
Merged, please reopen if still relevant 🙏
