### ISSUE TITLE
sessionx doesn't work with session names that have spaces

### ISSUE THREAD

**Issue by darricheng** [omerxx/tmux-sessionx#38]
If I rename my session to a name with a space, sessionx returns an invalid session.

For example, if I name my session `some session name`, the session will appear as `somesessionname` in sessionx with the error `Unknown session: somesessionname`.
<img width="1309" alt="Screenshot 2024-01-24 at 9 05 39 PM" src="https://github.com/omerxx/tmux-sessionx/assets/77005864/2cb0fa36-1241-4385-97cf-0361c96de817">

**Comment by yakloinsteak** [comment]
I'm working on a fix: https://github.com/yakloinsteak/tmux-sessionx/pull/1 which works for me, but I haven't had time to fully test it yet.
