### ISSUE TITLE
Option to disable preview mode entirely

### ISSUE THREAD

**Issue by Murderlon** [omerxx/tmux-sessionx#39]
I really like this plugin but I don't need the preview as it's just distracting. Can we get an option to disable it?

**Comment by Murderlon** [comment]
Update: `set -g @sessionx-preview-ratio '0%'` does work but perhaps an explicit option is still nice, ideally where we don't even run the script instead of just hiding it.

**Comment by omerxx** [comment]
@Murderlon Nice solution!
Should be relatively easy to implement
