### ISSUE TITLE
a way to change the window size and ratio and placement of preview 

### ISSUE THREAD

**Issue by conXDlation** [omerxx/tmux-sessionx#4]
window size is easier said than done but the next two arent if im not wrong. as you would never have to much text in the search side of things having 1:1 with respect to the preview is not optimal. that said placement of preivew mabe be bellow so it would have an more area and more width which is better than hight but still this is not necceary if you can change the ratio of the preview window. any one of the last two will be enough you can try both if you have nothing to do for the weekend ;)

**Comment by omerxx** [comment]
@conXDlation See the new options in the readme. Also the default now is having the preview on top for more screen space. Good idea and better looking default.
