### ISSUE TITLE
[Feature Request] Additional config options

### ISSUE THREAD

**Issue by markfeinstein** [omerxx/tmux-sessionx#40]
It would be great to have more options to customzie the sessionx popup. I am specifically looking for layout (to reverse the input position) and prompt customization, but something to more generically add fzf window options may be more beneficial.

**Comment by omerxx** [comment]
Hey! can you create a short list of useful features you'd like to be able to customize?
- reverse input position - relatively simple
- prompt - what would you like to change? icons / placeholders?

**Comment by ProgmRuanSilva** [comment]
Hey guys, I've created a new PR to make it #43
