### ISSUE TITLE
Want to set a keymap for selecting previous and next item, but the plugin keeps crashing.

### ISSUE THREAD

**Issue by shibisuriya** [omerxx/tmux-sessionx#46]
I tried to set these keymaps but the plugin is not opening...

set -g @sessionx-bind-select-up 'C-p'
set -g @sessionx-bind-select-down 'C-n'

Also even after I remove these keymaps from the tmux.conf file, the plugin doesn't open... I make the sessionx dialog to open I have to then set,

set -g @sessionx-bind-select-up 'alt-p'
set -g @sessionx-bind-select-down 'alt-n'

**Comment by ProgmRuanSilva** [comment]
try set the keymap : 'ctrl-p' and 'ctrl-n'

**Comment by shibisuriya** [comment]
Thanks, I found out the issue @ProgmRuanSilva,  I tried setting 'ctrl-p' and 'ctrl-n', but the issue was there is already a default keymap (@sessionx-bind-scroll-up) that uses 'ctrl-p', so I also had to set "@sessionx-bind-scroll-up to something else like 'ctrl-u' so that session-x picks up the my keymaps...

This appropriate behavior should be to override the default keymaps? But the plugins works...

**Comment by ProgmRuanSilva** [comment]
In the project documentation, the keybind setted is C-p.
 
Now I understand why you had put it. 

I will change the comment in the documentation
