### ISSUE TITLE
The icon is overlapping with the text, not important but looks bad.

### ISSUE THREAD

**Issue by shibisuriya** [omerxx/tmux-sessionx#48]
![image](https://github.com/omerxx/tmux-sessionx/assets/69033713/7dc7c169-3dc0-48ca-bbbd-2b8976232b56)

**Comment by ProgmRuanSilva** [comment]
Question: Did you change the prompt or is it what comes by default?

**Comment by shibisuriya** [comment]
@ProgmRuanSilva I did not change the prompt, this is something that came out of the box when I installed the plugin using tpm...

**Comment by shibisuriya** [comment]
I use hack nerd fonts with alacritty btw.

**Comment by ProgmRuanSilva** [comment]
Right, I'll try to solve this bug

**Comment by fvincenzo** [comment]
@ProgmRuanSilva sorry I had the same issue and could not resist to debug it 😄 

@shibisuriya can you please try if it works for you?

**Comment by ProgmRuanSilva** [comment]
> @ProgmRuanSilva sorry I had the same issue and could not resist to debug it 😄 
> 
> @shibisuriya can you please try if it works for you?

Tanks for it

**Comment by shibisuriya** [comment]
![image](https://github.com/omerxx/tmux-sessionx/assets/69033713/db6994ca-c7a8-4b9e-9311-280a0195f3c9)
I have substituted @fvincenzo's repo, and issued <prefix>I (make tpm install plugins listed in tmux.conf) but the icon is not changing...

![image](https://github.com/omerxx/tmux-sessionx/assets/69033713/5412b8b4-6d67-4524-b756-a5488d1910d9)

I tried to manually set the prompt icon to make it look better but when I removed that setting from tmux.conf the default prompt icon is not getting loaded... I feel like there is some sort of cache that needs to be cleared...

will only be able to validate @fvincenzo's changes if I am able to clear the cache...

**Comment by shibisuriya** [comment]
I restarted my machine, the @fvincenzo's patch seems to work fine, thank you... Can merge.

**Comment by fvincenzo** [comment]
@shibisuriya I forgot to mention that you had to restart tmux server after the change. 

@shibisuriya @ProgmRuanSilva can you please give +1 to the patch so that @omerxx sees it?

**Comment by shibisuriya** [comment]
Thanks @fvincenzo!

**Comment by ProgmRuanSilva** [comment]
Thanks @fvincenzo and @shibisuriya to contribute and open the issue
