### ISSUE TITLE
Need provision to enable cycling through the list... 

### ISSUE THREAD

**Issue by shibisuriya** [omerxx/tmux-sessionx#51]
Can we get a flag which enables the user to cycle through the fzf items which he selects next or previous?

**Comment by omerxx** [comment]
@shibisuriya that's actually rather simple with FZF using `--cycle`
I'll add the option

**Comment by omerxx** [comment]
@shibisuriya There's an option in the plugin to set your own fzf flags, essentially letting you do this:
```
set -g @sessionx-additional-options "--cycle"
```

Does this answer the requirement?
