### ISSUE TITLE
💬 Would be awesome to be able to pass in FZF options

### ISSUE THREAD

**Issue by ttdotsh** [omerxx/tmux-sessionx#54]
The primary thing I'd like to see is the ability to customize FZF colors/theme. I can definitely see that the implementation could be challenging, but would you be open to a PR to add this?

**Comment by ProgmRuanSilva** [comment]
Hey @ttdotsh thanks for interessing to contribute

see [here to open a pull request from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

1. Make a fork of the project
2. Make your changes 
3. Open a pull request

**Comment by ttdotsh** [comment]
@ProgmRuanSilva I took a whack at this [here](https://github.com/omerxx/tmux-sessionx/pull/59) and have the functionality mostly working, save for a bug with some fzf options like `--bind`. I spent a majority of my day today trying to resolve that and I am stuck. Would love it if someone could take a look (no hard feelings though if nobody gets to it)

**Comment by ProgmRuanSilva** [comment]
@ttdotsh I've commented on your PR
