### ISSUE TITLE
Setting `C-p` and `C-n` kebindings breaks the plugin

### ISSUE THREAD

**Issue by Mseller** [omerxx/tmux-sessionx#58]
Hello! First, thanks for the awesome plugin!

I had some issues trying to set the following keybindings for the plugin.

```
set -g @sessionx-bind-scroll-up 'C-p'
set -g @sessionx-bind-scroll-down 'C-n'
```

or

```
set -g @sessionx-bind-select-up 'C-p'
set -g @sessionx-bind-select-down 'C-n'
```

If I set these and start the plugin, the popup flashes and never gets started. If, however, I remove these keybindings, kill tmux server, and restart, everything works as expected. 

The config is really simple with just these additional settings:

```
set -g @sessionx-bind 'o'
set -g @sessionx-window-mode 'on'
```

And my `fzf` version is: 0.46.1 (3c0a630)

**Comment by ProgmRuanSilva** [comment]
Hello @Mseller thanks for opened the issue

The correct keybinds are the ctrl-p and ctrl-n. sorry for the confusion

I've opened a pull request #53 to fix this issue

Other users have the same confusion
