### ISSUE TITLE
latest changes from PR #57 break tmux-sessionx again.

### ISSUE THREAD

**Issue by mayersj1** [omerxx/tmux-sessionx#67]
After the latest commit of tmux-sessionx, attempting to switch between sessions in the sessionx window is broken again.  Attempting to switch to any session results in the following error:

'/Users/smayer/.tmux/plugins/tmux-sessionx/scripts/sessionx.sh' returned 1 and another session is created rather than switching to the one that was selected.

**Comment by Andreasgdp** [comment]
I've been getting this error as well.

**Comment by omerxx** [comment]
I just updated to the latest and not seeing this, is this still happening?
@ProgmRuanSilva Are you seeing this as well?

**Comment by infinite-ops** [comment]
I have the issue too, it seems to be from around the changes to do with not removing spaces in session names. I've gone back to 66d340e where things work.

**Comment by omerxx** [comment]
@ProgmRuanSilva @yakloinsteak Can you guys have a look and see whether this reproduces / whether something's wrong and needs reverting?

**Comment by yakloinsteak** [comment]
Could the people on this thread share their OS and the version of `sed` from `sed --version`? I have a suspicion it's related to one of those things (particularly using the stock `sed` on a Mac). I'm running Ubuntu 22 with GNU sed 4.8, and I'll try to get my hands on a Mac tomorrow to test out my hunch.

**Comment by infinite-ops** [comment]
fedora 39
sed 4.8-14

**Comment by yakloinsteak** [comment]
Thanks, @infinite-ops . Would you mind sharing the sessionx part of your `.tmux.conf` file, and could you provide the path you selected and the name/path of the session that it incorrectly takes you to?

**Comment by infinite-ops** [comment]
hi @yakloinsteak 
```
set -g @plugin 'omerxx/tmux-sessionx'
set -g @sessionx-window-mode 'on'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-bind-scroll-down 'alt-j'
set -g @sessionx-bind-scroll-up 'alt-k'
```

With latest it happens on anything. I seems to create a new session instead of matching an existing session.  I'll search for neovim and it'll find it in the search list but hitting enter it creates a new session called neovim_1 and then complains

existing tmux with a session called neovim
![2024-04-01_10-39](https://github.com/omerxx/tmux-sessionx/assets/61462677/fc538084-36d0-42f1-9870-98d48e11be2d)

changing to main and prefix o and searching for neovim finds it I hit enter but it creates this neovim_1 session and complains
![2024-04-01_10-34](https://github.com/omerxx/tmux-sessionx/assets/61462677/981f403c-04b5-4a99-9aa6-9fec1527801e)

So now I have two sessions
![2024-04-01_10-38](https://github.com/omerxx/tmux-sessionx/assets/61462677/d2c044b7-b6c8-4736-84ae-dee2a63a9811)

**Comment by infinite-ops** [comment]
just on the off chance I hadnt completely closed tmux (I tend to always have it running) I started fresh with main and its the same behavior
![2024-04-01_10-45](https://github.com/omerxx/tmux-sessionx/assets/61462677/e5870ce6-baa7-472a-a603-8085bf595676)

**Comment by yakloinsteak** [comment]
That's helpful information. I'll try to get a fix done tonight. Maybe we revert if I can't get to the bottom of it tonight, and it might have to do with having no alternate paths set.

**Comment by Andreasgdp** [comment]
Arch
sed v.4.9

`tmux.conf`
```
set -g @plugin 'omerxx/tmux-sessionx'
set -g @sessionx-bind '^o'
set -g @sessionx-window-mode 'on'
```

**Comment by yakloinsteak** [comment]
This seems to occur when `sessionx-window-mode` is set to `on`. I definitely have enough information to fix this now that I can reproduce it myself.

**Comment by yakloinsteak** [comment]
I'll do a little more testing, but I believe my PR keeps spaces in session names and paths working while fixing the issue with window-mode being on. I'll make it non-draft within an hour unless I find some big problem with it.

**Comment by infinite-ops** [comment]
nice! just took 5c7d1bd for a spin and it solves the issues I had!

**Comment by yakloinsteak** [comment]
Great! There are still edge cases like paths with dots and colons, but I can't get it to break with what are probably normal conditions. I'll make it non-draft. Thanks for testing, @infinite-ops
