### ISSUE TITLE
alt-bspace does not work

### ISSUE THREAD

**Issue by mmammel12** [omerxx/tmux-sessionx#68]
All of the keybinds in sessionx work except for `alt-bspace`. I am on a mac laptop and have tried the keybind using my glove80 as well as the built in keyboard and get no response. My tmux config can be found [here](https://github.com/mmammel12/tmux/blob/main/tmux.conf). It would be nice to be able to rebind these keys.

**Comment by Myzel394** [comment]
Did you find a solution?

**Comment by mmammel12** [comment]
@Myzel394 yes, I looked through the code and found that [it can be rebound](https://github.com/omerxx/tmux-sessionx/blob/8c4ec54a3f7c1e42e0c4c4bcd4bb6853577581b4/scripts/sessionx.sh#L49) but it was not documented in the readme.
[Here](https://github.com/mmammel12/tmux/blob/17ec029d4295b6f23f2c3669bf36f7da7eb5d511/tmux.conf#L32) is how I set it in my config:
```
set -g @sessionx-bind-kill-session "ctrl-y"
```
