### ISSUE TITLE
Can we get provision to go back to the previous session and go forward to the next session?

### ISSUE THREAD

**Issue by shibisuriya** [omerxx/tmux-sessionx#73]
Currently tmux ships with the <prefix> + L that lets me hope back to the previous session... When I am in the previous session
and press <prefix> + L it brings me back to the session that I began with... 

I thought it would be a great idea if I am somehow able to go back, back, back, then forward, forward, forward between sessions... 

Like undo and redo...

**Comment by omerxx** [comment]
I think `L` is used for windows, `()` are for sessions:
> (           Switch the attached client to the previous session.
)           Switch the attached client to the next session.

What you mean here is to have a binding to show the last session *while in sessionx*? As in, while viewing the list of sessions?

**Comment by shibisuriya** [comment]
Got it using <prefix> + (  and <prefix> + ) does the job well, thank you.
