### ISSUE TITLE
Am I confused??    Preview only shows pane0 of the window??

### ISSUE THREAD

**Issue by cavanaug** [omerxx/tmux-sessionx#78]
Is this the expected behavior??

I have a window with multiple panes, but during preview Im only session pane0.

**Comment by omerxx** [comment]
You're not confused!
`preview.sh` actually does handle `-s` for session preview but it's not exposed because the pop up preview was never made to handle a full session. Would you like to have it as an option? does it make sense to you?

**Comment by omerxx** [comment]
You should be able to see additional panes, maybe with slightly wider settings?
![image](https://github.com/omerxx/tmux-sessionx/assets/12237955/d4812635-760e-42a4-ac33-c739fa849868)

**Comment by cavanaug** [comment]
![image](https://github.com/omerxx/tmux-sessionx/assets/59479/d0d4a551-f22b-4da8-8fa4-3bfadcec0441)

You can see on the side where I have session 4 in a two pane horizontal split, but when sessionx previews it, you only see the top pane0.

**Comment by omerxx** [comment]
I'm sorry. You're right I misread your issue. Yes the current preview uses `tmux capture-pane` and fetches the active pane from the session you're on.
The way around it is using the `window_mode` where you can browse a list of windows inside sessions.
I was looking for a way to construct the view and eded up not bothering with presenting everything in a small preview window.

If you think it's necessary and have a better way of presenting please share!

**Comment by cavanaug** [comment]
I think even when using the window-mode (C-M) it only shows the active pane.     In this regard, I think the native choose-tree is better because it actually shows the multiple panes.   I dunno, maybe tmux itself could expose a capture-window that uses the same logic as how the preview is handled in choose-tree.

Net, net, this is the expected behavior,  so Ill close this...

**Comment by omerxx** [comment]
@cavanaug This was exactly my request / when I tried searching.
Even the Tmux preview itself (`prefix+S`) reconstructs it's own layout of `capture-pane` (not necessarily in the order they are laid on the screen.

If anyone ever wants to construct this in the plugin's preview I'm more than happy to explore :)
