### ISSUE TITLE
Sessionx ignoring ctrl-p keybind for select up/down, works with different config of e.g. ctrl-y

### ISSUE THREAD

**Issue by Andreasgdp** [omerxx/tmux-sessionx#79]
Unable to use ctrl-p as a binding for select up or down. 

For some reason using `ctrl-p` as a keybind does not seem to work for me for select up or down

Sessionx tmux config
```
# sessionx config
set -g @plugin 'omerxx/tmux-sessionx'
set -g @sessionx-bind '^o'
set -g @sessionx-window-mode 'on'
set -g @sessionx-bind-select-up 'ctrl-n'
set -g @sessionx-bind-select-down 'ctrl-p'
set -g @sessionx-zoxide-mode 'on'
```

NOTE: I have tested that it works for at least some other operations like:
```
set -g @sessionx-bind-rename-session 'ctrl-p'
```

**Comment by omerxx** [comment]
You're right.
It's been taken by `bind_scroll_up` for no good reason (even the docs say `ctrl-p`)
I'm going to fix it soon but in the meantime feel free to override your binding:

```
set -g "@sessionx-bind-scroll-up" "<something that's not ctrl-p>" 
```
