### ISSUE TITLE
Current session not in the list - sometimes

### ISSUE THREAD

**Issue by stepanzak** [omerxx/tmux-sessionx#8]
When I first enter the sessionx menu with \<prefix>+O, there are all sessions except the current one.
When I select any of them and press \<C-r> and rename it to anything (or just press enter to leave it the same), the current session also appears on the list.
This happens only when I have more sessions than one.

System info:
OS: EndeavourOS Linux (Arch based)
Shell: ZSH
Latest version of everything

<details><summary>Screenshots:</summary>
<p>

![image](https://github.com/omerxx/tmux-sessionx/assets/99094176/740aa6ef-090a-4a24-8fb5-e7da52653cab)

![image](https://github.com/omerxx/tmux-sessionx/assets/99094176/031b97e5-2379-43bb-a98d-b2fc9bef1cc5)

![Screenshot_20231210_211816](https://github.com/omerxx/tmux-sessionx/assets/99094176/5e42a634-a40c-4ce0-ac92-f6c025ec9bdf)
</p>
</details>

**Comment by omerxx** [comment]
Yep, actually that was done intentionally to filter out the current session on first glance for the quick switch which is 90% of my use of the plugin.
After rename I bring it back assuming the user is running organization tasks and would want to rename the current session as well.

That said, I understand it's not a consistent behaviour and feels awkward. 
WDYT?

**Comment by stepanzak** [comment]
Hmm, it actually makes lot of sense when you say it. Showing the current session is AFAIK useful only for renaming and for that you usually use \<prefix>+$.
The problem is that it's confusing.
I would suggest either:
- always show current session but always list it as last item (not sure if it's possible in FZF
- make a keybinding to toggle it's visibility
- leave the behavior as is but clearly communicate it in the README or even in the program (not sure how, maybe after renaming session show a text _current session shown_ somewhere?)
- don't show it at all
I'm not a UX expert or anything though, this is just what was on top of my head
