### ISSUE TITLE
I don't see proper font characters, think there's a missing prereq

### ISSUE THREAD

**Issue by SolverDude** [omerxx/tmux-sessionx#84]
Thanks for this tool and your blog and videos.  I'm new to your world, but i like the tips and tools you present..

After configuring my .tmux.conf as you (actuallly using yours) instead of what I see in the video, I see this:
<img width="505" alt="Screenshot 2024-04-18 at 8 48 33 AM" src="https://github.com/omerxx/tmux-sessionx/assets/7353239/d34dea44-8225-4194-b838-14869fdd44ae">

I guessed maybe you needed nerd fonts, so i then did a `brew install font-hack-nerd-font` and restarted tmux.  no joy.  Is there a prerequisite not reflected in the README.md?

I don't know this world enough to know how to continue, I looked for `font` unsuccessfully in the code here.

Sorry I can't figure this out myself but I appear to be at an empasse (aesthetically at least, things work fine, just annoys me).  This is from a mac m3 if that somehow comes into play.

**Comment by SolverDude** [comment]
Looks like catpuccin plugin needed another terminal.  i watched your UX video and heard that you were using [WezTerm](https://wezfurlong.org/wezterm/index.html) and switching to that solved this.

The above was with iterm2.  There was an option to use fonts for non-ascii chars, but that made no diff.

I also tried Alacritty, which I didn't get to work either.

Anyways, maybe this will help another newbie, and perhaps the README.md could use some love to warn/guide, but really not directly this link in a great toolchain but with a lot of toolchain links...so maybe this is a video issue in lieu of your repos, haha!  Close/adapt this Issue at your discretion...

I appreciate the intel and the videos, again.

**Comment by omerxx** [comment]
Hey @SolverDude and thanks for this!
I'll close the issue, but if you'd like to contribute a README warning / suggestion go ahead :)
