### ISSUE TITLE
Ubuntu 22 LTS - fzf-tmux error: `unknown option: --border-label`

### ISSUE THREAD

**Issue by TechDufus** [omerxx/tmux-sessionx#9]
I'm not sure if this is a difference in `fzf-tmux` versions installed via `apt` vs `homebrew` or otherwise, but I've installed `fzf` via `apt` on **Ubuntu 22 LTS** and the latest version that I can install currently is `fzf 0.29.0-1`

```bash
fzf --version
0.29 (devel)
```
```bash
fzf-tmux --version
fzf-tmux (with fzf 0.29 (devel))
```

If I manually go into my locally installed plugin and remove [this line](https://github.com/omerxx/tmux-sessionx/blob/d71e51b4be2e94ca5d92f5f8afcc190ac56980f1/scripts/sessionx.sh#L48) then this all works (as for as I've briefly tested) on Ubuntu.

https://github.com/omerxx/tmux-sessionx/blob/d71e51b4be2e94ca5d92f5f8afcc190ac56980f1/scripts/sessionx.sh#L48

**Comment by omerxx** [comment]
Hmmm. I wonder whether it's worth to remove all together or add a config variable specific for fzf `devel`.
WDYT?

**Comment by omerxx** [comment]
@TechDufus Any chance this is a 2 years old fzf release (https://github.com/junegunn/fzf/releases/tag/0.29.0)?
Care to upgrade and check again?

**Comment by TechDufus** [comment]
Let me build out my dotfiles to dynamically get the latest github release for fzf instead of relying on `apt` packages and see if that works... :) Please hold.

**Comment by TechDufus** [comment]
✅ Good to go... I'm no longer installing `fzf` via `apt`. I'm following their `git` instructions to clone and run their install script.

I use `ansible` for my dotfiles, so that's how I'm cloning and installing.

https://github.com/TechDufus/dotfiles/blob/5b3c2eeabc3a377a543da3e69b2d0baeb719ebdd/roles/fzf/tasks/ubuntu.yml#L2-L11

**Comment by omerxx** [comment]
Closing. If anything changes let me know
