### ISSUE TITLE
Preview Window Disabled - still uses space

### ISSUE THREAD

**Issue by mvaldes14** [omerxx/tmux-sessionx#91]
I'd like to keep a minimal session switcher so i have the following overrides on the plugin

```
set -g @sessionx-bind 's'
set -g @sessionx-preview-enabled 'false'
set -g @sessionx-x-path '~/git'
set -g @sessionx-preview-ratio '0%'
set -g @sessionx-window-height '30%'
set -g @sessionx-window-width '75%'
```

I'd expect it to just list out the session for me to pick from and move quickly but somehow the preview panel space still shows up. See below.

![1](https://github.com/omerxx/tmux-sessionx/assets/20586114/93f7db4b-fed9-4455-8265-ff86a90fb50f)

**Comment by omerxx** [comment]
Using your exact config this is what I get:
<img width="1286" alt="image" src="https://github.com/omerxx/tmux-sessionx/assets/12237955/4d7044a7-95e4-4b4c-bc9e-65edd264c722">

Can you please - 
1. Make sure your sessionx is up to date
2. Share your fzf + tmux versions?

This is mine:
```
~ ❯ fzf --version
0.46.1 (brew)
~ ❯ tmux -V
tmux 3.4
```

**Comment by mvaldes14** [comment]
Versions

```
fzf --version
0.44.1 (0.44.1)
tmux -V
tmux 3.3a
```

**Comment by omerxx** [comment]
I still can't really reproduce, unless I'm setting a larger height in which case the gap is created.

Is it possible that your resolution dictates that 30% is the window you got?
Can you set it to something smaller like 20% and see whether things change?

**Comment by mvaldes14** [comment]
moved it down to 25% and it looks better now, curious why its trying to keep that space.
tried to pass down custom fzf parameters but seems like those only affect the pointers/pickers.

guess we can close this for now.
appreciate the help!

**Comment by omerxx** [comment]
@mvaldes14 I'm also curious about why this is happening.
If this is reproducing / annoying for you or anyone visiting this in the future, please reopen
